---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkite-agent
  labels:
    app: buildkite-agent
  namespace: buildkite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: buildkite-agent
  template:
    metadata:
      labels:
        app: buildkite-agent
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - image: 127.0.0.1:5000/buildkite-authelia
        name: buildkite-authelia
        securityContext:
          privileged: true
        env:
        - name: BUILDKITE_AGENT_NAME
          value: clems4ever-agent
        - name: BUILDKITE_AGENT_TOKEN
          valueFrom:
            secretKeyRef:
              name: buildkite-agent
              key: token
        - name: SSH_PRIVATE_RSA_KEY
          valueFrom:
            secretKeyRef:
              name: thirdparties-credentials
              key: id_rsa
        - name: BUILDKITE_AGENT_TAGS
          value: build=true,suite=all,suite=kubernetes
        - name: BUILDKITE_AGENT_PRIORITY
          value: "4"
        - name: PUID
          value: "1000"
        - name: GUID
          value: "1000"
        - name: TZ
          value: France/Paris
        volumeMounts:
        - mountPath: /buildkite/.go
          name: go-cache
        - mountPath: "/lib/modules"
          name: lib-modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
        - mountPath: /data/buildkite
          name: credentials
        - mountPath: /var/lib/docker
          name: docker
      volumes:
        - name: go-cache
          hostPath:
            path: /data/buildkite/.go
            type: Directory
        - name: lib-modules
          hostPath:
            path: /lib/modules
            type: Directory
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
        - name: docker
          emptyDir: {}
        - name: credentials
          secret:
            secretName: thirdparties-credentials
            items:
            - key: environment
              path: hooks/environment
            - key: config.json
              path: .docker/config.json

