version: '2.1'

networks:
  net:
    driver: bridge

services:

  registrycache:
    image: registry:2
    container_name: registrycache
    volumes:
      - /path/on/host/registryproxy.yml:/etc/docker/registry/config.yml
      - /path/on/host/registry:/var/lib/registry
    networks:
      - net
    restart: unless-stopped

  buildkite1:
    image: authelia/buildkite
    container_name: buildkite1
    privileged: true
    volumes:
      - /path/on/host/docker:/buildkite/.docker
      - /path/on/host/ssh:/buildkite/.ssh
      - /path/on/host/go:/buildkite/.go
      - /path/on/host/hooks:/buildkite/hooks
    networks:
      - net
    restart: unless-stopped
    environment:
      - BUILDKITE_AGENT_NAME=named-node-1
      - BUILDKITE_AGENT_TOKEN=
      - BUILDKITE_AGENT_TAGS=
      - BUILDKITE_AGENT_PRIORITY=
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne

  buildkite2:
    image: authelia/buildkite
    container_name: buildkite2
    privileged: true
    volumes:
      - /path/on/host/docker:/buildkite/.docker
      - /path/on/host/ssh:/buildkite/.ssh
      - /path/on/host/go:/buildkite/.go
      - /path/on/host/hooks:/buildkite/hooks
    networks:
      - net
    restart: unless-stopped
    environment:
      - BUILDKITE_AGENT_NAME=named-node-2
      - BUILDKITE_AGENT_TOKEN=tokenhere
      - BUILDKITE_AGENT_TAGS=
      - BUILDKITE_AGENT_PRIORITY=
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne

  buildkite3:
    image: authelia/buildkite
    container_name: buildkite3
    privileged: true
    volumes:
      - /path/on/host/docker:/buildkite/.docker
      - /path/on/host/ssh:/buildkite/.ssh
      - /path/on/host/go:/buildkite/.go
      - /path/on/host/hooks:/buildkite/hooks
    networks:
      - net
    restart: unless-stopped
    environment:
      - BUILDKITE_AGENT_NAME=named-node-3
      - BUILDKITE_AGENT_TOKEN=tokenhere
      - BUILDKITE_AGENT_TAGS=
      - BUILDKITE_AGENT_PRIORITY=
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne