#!/command/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" buildkite
usermod -o -u "$PUID" buildkite

if [[ -n "${DOCKER_GID:-}" ]]; then
  if ! getent group "${DOCKER_GID}" > /dev/null; then
    groupadd -o -g "${DOCKER_GID}" dockerhost
  fi

  usermod -aG "$(getent group "${DOCKER_GID}" | cut -d: -f1)" buildkite
fi

cat <<'EOF'
--------------------------------------------
   / \  _   _| |_| |__   ___| (_) __ _
  / _ \| | | | __| '_ \ / _ \ | |/ _` |
 / ___ \ |_| | |_| | | |  __/ | | (_| |
/_/   \_\__,_|\__|_| |_|\___|_|_|\__,_|
                ____ ___
               / ___|_ _|
              | |    | |
              | |___ | |
               \____|___|
--------------------------------------------
GID/UID
--------------------------------------------
EOF
echo "User uid:    $(id -u buildkite)
User gid:    $(id -g buildkite)
User groups: $(id -Gn buildkite)
--------------------------------------------
"
chown -R buildkite:buildkite /buildkite
