#!/command/with-contenv bash

until curl -s --unix-socket /var/run/docker.sock http/_ping 2>&1 >/dev/null; do sleep 1; done

if ! docker buildx ls | grep -q buildx; then
  docker buildx create --driver-opt image=moby/buildkit:master --name buildx --use && \
  docker buildx inspect --bootstrap && \
  chown -R buildkite:buildkite /buildkite/.docker
fi

s6-setuidgid buildkite docker buildx use default
