#!/command/with-contenv bash

if docker buildx ls | grep -L buildx; then
  docker buildx create --driver-opt image=moby/buildkit:master --name buildx --use && \
  docker buildx inspect --bootstrap && \
  chown -R buildkite:buildkite /buildkite/.docker
fi

s6-setuidgid buildkite docker buildx use default
